education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('webadmin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# change to aws s2 bucket in production

webadmin/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('my-courses', views.my_courses, name='my_courses'),
    path('lessons/<str:slug>', views.lessons, name='lessons'),
    path('<str:slug>', views.course, name='course'),
]

webadmin/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    banner = models.ImageField(upload_to='course')
    price = models.FloatField()

    def __str__(self):
        return self.title   
    

class Student(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    courses = models.ManyToManyField(Course, through='CourseStudent')

    def clean(self):
        """Garante que idUnidadeSuperior não seja atribuída a sí mesma."""
        if self.name == self.email:
            raise ValidationError("Não é permitido email e nomes iguais")
    
    def __str__(self):
        return self.name

class Test(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)    
    description = models.TextField()
    completed = models.BooleanField()

    def __str__(self):
        return self.description[:50]


class Promotion(models.Model):
    description = models.CharField(max_length=255)
    percent = models.FloatField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    active = models.BooleanField()

    def __str__(self):
        return self.description
class Payment(models.Model):
    value = models.FloatField()
    paid = models.BooleanField(default=False)
    payment_date = models.DateField(null=True)
    promotion = models.ForeignKey(Promotion, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    recurrent = models.BooleanField(default=False)

    def __str__(self):
        return self.student.name + '-' + str(self.value)

class CourseStudent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.DO_NOTHING)
    payment = models.ForeignKey('Payment', on_delete=models.DO_NOTHING, null=True)
    rate = models.IntegerField(null=True)
    comments = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    grade = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.student.name + '-' + self.course.title

class Module(models.Model):
    name = models.CharField(max_length=255)    
    completed = models.BooleanField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    #topics = models.ManyToManyField(Topic, through='TopicModule')
    #questions = models.ManyToManyField(Question, through='QuestionModule')

    def __str__(self):
        return self.name

class Topic(models.Model):
    title = models.CharField(max_length=255)
    video = models.CharField(max_length=250)
    duration = models.IntegerField()
    module = models.ForeignKey(Module, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Question(models.Model):
    description = models.TextField()
    comment = models.CharField(max_length=50)    
    module = models.ForeignKey(Module, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

class Choice(models.Model):
    description = models.CharField(max_length=50)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.BooleanField()

    def __str__(self):
        return self.description

class Resource(models.Model):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    module = models.ForeignKey(Module, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

webadmin/views.py
from django.shortcuts import render
from .models import Course, Module, CourseStudent, Payment, Promotion, Student
from django.http import HttpResponse

# Create your views here.

def index(request):
    """Cria a página inicial do portal"""
    courses_list = Course.objects.order_by('-title')
    context = {'courses_list': courses_list}
    return render(request, 'index.html', context)

def course(request, slug):
    """Cria a página de um curso"""

    course = Course.objects.get(slug=slug)
    modules = Module.objects.filter(course=course)
    context = {'course': course,
               'modules': modules
               }
        
    if request.method == 'POST':
        email = request.session.get('email', None)

        if email is None:
            return render(request, 'login.html', context)

        student = Student.objects.get(email=email)
        zero_promotion = Promotion.objects.get(description='zero')
        
        payment = Payment(
            value = course.price,
            paid = False,
            promotion = zero_promotion,
            student = student,
            course = course,
            recurrent = False,
        )
        if request.POST.get('promotion', None) is not None:
            promotion = Promotion.objects.get(description=request.POST.get('promotion'))
            payment.promotion = promotion
            payment.value = payment.value - (payment.value * promotion.percent / 100)
        payment.save()
        
    
    return render(request, 'course.html', context)


def my_courses(request):
    """Cria a página de meus cursos"""
    email = request.session.get('email', None)
    if email is None:
        return render(request, 'login.html', {})
    
    student = Student.objects.get(email=email)
    courses = CourseStudent.objects.filter(student=student)
    context = {'courses_list': courses}
    return render(request, 'my_courses.html', context)


def lessons(request, slug):
    """Cria a página de um curso"""

    email = request.session.get('email', None)
    if email is None:
        return render(request, 'login.html', {})

    course = Course.objects.get(slug=slug)
    modules = Module.objects.filter(course=course)
    context = {'course': course,
               'modules': modules
               }
        
    
    return render(request, 'lesson.html', context)


## Authentication methods

def login(request):
    """Cria a página de login"""
    if request.method == 'POST':
        user = Student.objects.get(email=request.POST.get('email'))
        if user.password == request.POST.get('password'):
            request.session['username'] = user.name
            request.session['email'] = user.email
            if not request.POST.get('remember_me', False):
                request.session.set_expiry(0)
            return render(request, 'index.html', {'courses_list': Course.objects.order_by('-title')})
        else:
            return render(request, 'login.html', {'error_message': 'Senha inválida'})
    else:
        return render(request, 'login.html', {})


def logout(request):
    """Cria a página de logout"""
    request.session['username'] = None
    request.session['email'] = None
    return render(request, 'index.html', {'courses_list': Course.objects.order_by('-title')})


def register(request):
    """Cria a página de registro"""
    if request.method == 'POST':
        if request.POST.get('password1') != request.POST.get('password2'):
            return render(request, 'register.html', {'error_message': 'Senhas não conferem'})
        
        user = Student(
            name = request.POST.get('nome'),
            email = request.POST.get('email'),
            password = request.POST.get('password1'),
            phone = request.POST.get('telefone'),
            address = request.POST.get('endereco'),
        )
        try:
            user.save()
            request.session['username'] = user.name
            request.session['email'] = user.email
            return render(request, 'index.html', {'courses_list': Course.objects.order_by('-title'), 'success_message': 'Usuário cadastrado com sucesso'})
        except:
            return render(request, 'register.html', {'error_message': 'Email já cadastrado'})
    else:
        return render(request, 'register.html', {})

webadmin/templates/course.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  
  <main>
  
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-8 col-md-8 mx-auto">
          <h1 class="fw-light">{{ course.title }}</h1>
          <h3>R$ {{ course.price}}</h3>
          <form method="post">
            {% csrf_token %}
            <p>
              <button type="submit" class="btn btn-primary my-2">Comprar este curso</button>
              <a href="#" class="btn btn-secondary my-2">Aplicar cupom</a>
            </p>
          </form>
          
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="row">
          <div class="col">
            <div class="p-3 mb-3 bg-body border rounded">
              {{ course.description | safe }}
            </div>
          </div>
          <div class="col">
            <div class="accordion" id="accordionExample">
              {% for module in modules %}
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{module.id}}" aria-expanded="true" aria-controls="collapse{{module.id}}">
                    {{ module.name }}
                  </button>
                </h2>
                <div id="collapse{{module.id}}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    {% for topic in module.topic_set.all %}
                    <p>{{ topic.title }} - {{ topic.duration }}min</p>
                    {% endfor %}
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>

        
        
  
       

      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}

webadmin/templates/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              <li><a href="#" class="text-white">Follow on Twitter</a></li>
              <li><a href="#" class="text-white">Like on Facebook</a></li>
              <li><a href="#" class="text-white">Email me</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
          <strong>Cursos - Engenheiro Moderno</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>
  
  <main>
  
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Python Para Todos</h1>
          <p class="lead text-muted">Aprenda a programar, técnicas de engenharia de software, automação de tarefas maçantes e inteligência artifical na nossa plataforma de cursos.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Curso Gratuito de Python</a>
            <a href="#" class="btn btn-secondary my-2">Baixar ebook grátis</a>
          </p>
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for course in courses_list %}
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
  
              <div class="card-body">
                <p class="card-text">{{ course.title }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}

webadmin/templates/lesson.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  
  <main>
  
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-8 col-md-8 mx-auto">
          <h1 class="fw-light">{{ course.title }}</h1>
          <h3>R$ {{ course.price}}</h3>
          <form method="post">
            {% csrf_token %}
            <p>
              <button type="submit" class="btn btn-primary my-2">Comprar este curso</button>
              <a href="#" class="btn btn-secondary my-2">Aplicar cupom</a>
            </p>
          </form>
          
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="row">
          <div class="col">
            <div class="p-3 mb-3 bg-body border rounded">
              {{ course.description | safe }}
            </div>
          </div>
          <div class="col">
            <div class="accordion" id="accordionExample">
              {% for module in modules %}
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{module.id}}" aria-expanded="true" aria-controls="collapse{{module.id}}">
                    {{ module.name }}
                  </button>
                </h2>
                <div id="collapse{{module.id}}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    {% for topic in module.topic_set.all %}
                    <p>{{ topic.title }} - {{ topic.duration }}min</p>
                    {% endfor %}
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>

        
        
  
       

      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}

webadmin/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  
  <main>
  

  
    <div class="album py-5 bg-light">
      <div class="container">

        {% if error_message %}
          <div class="alert  alert-danger" role="alert">
            {{ error_message }}
          </div>
        {% endif %}
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
          <div class="col">
            <form method="post">
              {% csrf_token %}
              <h1 class="h3 mb-3 fw-normal">Por favor, faça login</h1>
          
              <div class="form-floating mb-3">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
                <label for="floatingInput">Email</label>
              </div>
              <div class="form-floating">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                <label for="floatingPassword">senha</label>
              </div>
          
              <div class="form-check text-start my-3">
                <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault" name="remember_me">
                <label class="form-check-label" for="flexCheckDefault">
                  Remember me
                </label>
              </div>
              <button class="btn btn-primary w-100 py-2 mb-3" type="submit">Entrar</button>
            </form>
            <a href="{% url 'register' %}" class="w-100 py-2">Criar conta</a>
          </div>
        </div>

      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}

webadmin/templates/my_courses.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  
  <main>
  
  
    <div class="album py-5 bg-light">
      <div class="container">

        {% if success_message %}
          <div class="alert  alert-success" role="alert">
            {{ success_message }}
          </div>
        {% endif %}
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for course in courses_list %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ course.course.banner.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" alt="{{ course.course.title }}">
              <div class="card-body">
                <p class="card-text">{{ course.course.title }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'lessons' course.course.slug %}" type="button" class="btn btn-sm btn-outline-secondary">Continuar</a>
                  </div>
                  <small class="text-muted">0 %</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}

webadmin/templates/register.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  
  <main>
  

  
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
          <div class="col">
            <form method="post">
              <h1 class="h3 mb-3 fw-normal">Por favor, faça seu cadastro</h1>
                
              {% csrf_token %}

              {% if error_message %}
              <div class="alert  alert-danger" role="alert">
                {{ error_message }}
              </div>
              {% endif %}

              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}

              <div class="form-floating mb-3">
                <input type="text" class="form-control" id="name" placeholder="name" name="nome">
                <label for="name">Nome</label>
              </div>
          
              <div class="form-floating mb-3">
                <input type="email" class="form-control" id="email" placeholder="name@example.com" name="email">
                <label for="floatingInput">Email</label>
              </div>

              <div class="form-floating mb-3">
                <input type="text" class="form-control" id="telefone" placeholder="(99) 99999-9999" name="telefone">
                <label for="telefone">Telefone</label>
              </div>

              <div class="form-floating mb-3">
                <input type="text" class="form-control" id="endereco" placeholder="Endereço" name="endereco">
                <label for="endereco">Endereço</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" class="form-control" id="password1" placeholder="Password" name="password1">
                <label for="password">Senha</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" class="form-control" id="password2" placeholder="Password" name="password2">
                <label for="password">Repetir Senha</label>
              </div>
          
            
              <button class="btn btn-primary w-100 py-2 mb-3" type="submit">Cadastrar</button>
            </form>
            <a href="{% url 'login' %}" class="w-100 py-2">Fazer login</a>
          </div>
        </div>

      </div>
    </div>
  
  </main>
  
  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

{% endblock %}